package s3j.annotations

import scala.annotation.StaticAnnotation

/**
 * When applied to a parameter serialized as object, continues serialization on same level instead of opening a nested
 * object. Could not be used when serializer for parameter's type is provided by implicit rather than generated by macro
 * itself (as macro needs to know exact set of keys that will occur in that object).
 * ==Example:==
 * {{{
 *   case class Test1(foo: Int)
 *   case class Test2(bar: String, @inlineObject t1: Test1)
 * }}}
 * Both `foo` and `bar` will be serialized on top level. Key `t1` will never be visible in serialization.
 */
class inlineObject extends StaticAnnotation
