package s3j.annotations

import scala.annotation.StaticAnnotation

/**
 * When applied to any type, forces macros to do implicit search instead of attempting to generate serializer. Ignored
 * on top level types, so implicit serializers could still be generated by macros even for marked types.
 */
class requireImplicit extends StaticAnnotation
